

// console.log("before error")
// throw new Error("Some custom error")
// console.log("after error")

try {
    console.log("before error")
    // throw new Error("Some custom error")
    console.log("111111")
}catch (e) {
    console.warn("Error happened ", e.message)
}

console.log("after error")


console.log("loop for")
///

console.log("loop while")

///